### ISSUE TITLE
Yahoo module not working?

### ISSUE THREAD

**Issue by pegasone** [mojotoad/Finance-QuoteHist#1]
I think the Yahoo module stopped working a while ago and only the Google module still returns historical data. Example URLs in the Yahoo.pm file return a 'Could not process this "GET" request' error. An atempt to download CSV data directly in the browser reaveals a URL that seems to have a different structure from those in the example URLs, suggesting that the syntax may have changed during the last year or so. Any ideas?

**Comment by pegasone** [comment]
OK, I see now that YQL queries for historical stock data are currently blocked. Yahoo/Verizon have yet to provide an explanation or an update on their plans re Yahoo Finance.

**Comment by lavrentius-dev** [comment]
Thank you, Matt, for v. 1.26!
